In [2]:
import pandas as pd
import numpy as np

In [13]:
# Generating basic DataFrame
data = np.arange(1, 21)
print("1d array:", data)

reshaped_data = data.reshape(5, 4)
print("\n 2d array:", reshaped_data)

df = pd.DataFrame(reshaped_data, columns=['A', 'B', 'C', 'D'])
print("\n DataFrame:", df)


1d array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

 2d array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

 DataFrame:     A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20


In [16]:
# Generating random DataFrame
df = pd.DataFrame({
    'A': np.random.rand(5),
    'B': np.random.rand(5)
})

print("DataFrame:", df)

DataFrame:           A         B
0  0.605971  0.183015
1  0.077071  0.145650
2  0.531105  0.844308
3  0.972675  0.282931
4  0.310864  0.019379


In [19]:
# with rows and columns names
data = np.arange(1, 21)
reshaped_data = data.reshape(5, 4)
df = pd.DataFrame(reshaped_data, index=['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], columns=['Column1', 'Column2', 'Column3', 'Column4'])
print(df)


      Column1  Column2  Column3  Column4
Row1        1        2        3        4
Row2        5        6        7        8
Row3        9       10       11       12
Row4       13       14       15       16
Row5       17       18       19       20


In [27]:
# Get top 5 rows
# if n is empty it will return the first 5 rows
n = 3
top_rows = df.head(n)
print("\nTop n rows:\n", top_rows)


Top n rows:
       Column1  Column2  Column3  Column4
Row1        1        2        3        4
Row2        5        6        7        8
Row3        9       10       11       12


In [30]:
# Get last 5 rows
# if n is empty it will return the last 5 rows
n = 3
bottom_rows = df.tail(n)
print("\nBottom n rows:\n", bottom_rows)


Bottom n rows:
       Column1  Column2  Column3  Column4
Row3        9       10       11       12
Row4       13       14       15       16
Row5       17       18       19       20


In [ ]:
# Getting columns datatype and non-null counts
df_info = df.info()
print("\nDataFrame Info:\n", df_info)   

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes

DataFrame Info:
 None
