In [1]:
import pandas as pd
import numpy as np

In [13]:
# Generating basic DataFrame
data = np.arange(1, 21)
print("1d array:", data)

reshaped_data = data.reshape(5, 4)
print("\n 2d array:", reshaped_data)

df = pd.DataFrame(reshaped_data, columns=['A', 'B', 'C', 'D'])
print("\n DataFrame:", df)


1d array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

 2d array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

 DataFrame:     A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20


In [14]:
# Generating random DataFrame
df = pd.DataFrame({
    'A': np.random.rand(5),
    'B': np.random.rand(5)
})

print("DataFrame:", df)

DataFrame:           A         B
0  0.729288  0.350330
1  0.198970  0.181211
2  0.158525  0.108594
3  0.853634  0.283908
4  0.436089  0.668207


In [15]:
# with rows and columns names
data = np.arange(1, 21)
reshaped_data = data.reshape(5, 4)
df = pd.DataFrame(reshaped_data, index=['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], columns=['Column1', 'Column2', 'Column3', 'Column4'])
print(df)


      Column1  Column2  Column3  Column4
Row1        1        2        3        4
Row2        5        6        7        8
Row3        9       10       11       12
Row4       13       14       15       16
Row5       17       18       19       20


In [16]:
# Get top 5 rows
# if n is empty it will return the first 5 rows
n = 3
top_rows = df.head(n)
print("\nTop n rows:\n", top_rows)


Top n rows:
       Column1  Column2  Column3  Column4
Row1        1        2        3        4
Row2        5        6        7        8
Row3        9       10       11       12


In [17]:
# Get last 5 rows
# if n is empty it will return the last 5 rows
n = 3
bottom_rows = df.tail(n)
print("\nBottom n rows:\n", bottom_rows)


Bottom n rows:
       Column1  Column2  Column3  Column4
Row3        9       10       11       12
Row4       13       14       15       16
Row5       17       18       19       20


In [ ]:
# Getting columns datatype and non-null counts
# This provides a quick overview of the DataFrame's structure
df_info = df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes


In [ ]:
# Describe DataFrame
# Get a statistical summary of the DataFrame
# This includes count, mean, std, min, 25%, 50%, 75%, max for each numeric column
df_description = df.describe()
print("\nDataFrame Description:\n", df_description)



DataFrame Description:
          Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    9.000000  10.000000  11.000000  12.000000
std     6.324555   6.324555   6.324555   6.324555
min     1.000000   2.000000   3.000000   4.000000
25%     5.000000   6.000000   7.000000   8.000000
50%     9.000000  10.000000  11.000000  12.000000
75%    13.000000  14.000000  15.000000  16.000000
max    17.000000  18.000000  19.000000  20.000000


In [67]:
## Indexing and selecting data in a DataFrame
# Display the original DataFrame
print("\nOriginal DataFrame:\n", df)

# Select a single column
# Single Column or Single row called a Series
column_1 = df['Column1']
print("Column1:\n", column_1)

# Select multiple columns
# Multiple columns are still a DataFrame
columns_1_2 = df[['Column1', 'Column2']]
print("\nColumns 1 and 2:\n", columns_1_2)

# Select rows by label using .loc
row_0 = df.loc['Row1']
print("\nRow 0:\n", row_0)

# Select multiple rows by label using .loc
rows_0_1 = df.loc[['Row1', 'Row2']]
print("\nRows 0 and 1:\n", rows_0_1)

# Select multiple rows by integer location using .iloc
rows_0_1 = df.iloc[0:3]
print("\nRows 0 and 1 (using iloc):\n", rows_0_1)

# Select multiple columns by integer location using .iloc
columns_1_2 = df.iloc[:, 1:3]
print("\nColumns 1 and 2 (using iloc):\n", columns_1_2)

# Select specific rows and columns using .iloc
# Bounded by the rows and columns specified (0 to 2 for rows and 1 to 3 for columns)
# This will select rows 0 and 1, and columns 1 and 2
specific_rows_columns = df.iloc[0:2, 1:3]
print("\nSpecific Rows and Columns (using iloc):\n", specific_rows_columns)



Original DataFrame:
       Column1  Column2  Column3  Column4
Row1        1        2        3        4
Row2        5        6        7        8
Row3        9       10       11       12
Row4       13       14       15       16
Row5       17       18       19       20
Column1:
 Row1     1
Row2     5
Row3     9
Row4    13
Row5    17
Name: Column1, dtype: int64

Columns 1 and 2:
       Column1  Column2
Row1        1        2
Row2        5        6
Row3        9       10
Row4       13       14
Row5       17       18

Row 0:
 Column1    1
Column2    2
Column3    3
Column4    4
Name: Row1, dtype: int64

Rows 0 and 1:
       Column1  Column2  Column3  Column4
Row1        1        2        3        4
Row2        5        6        7        8

Rows 0 and 1 (using iloc):
       Column1  Column2  Column3  Column4
Row1        1        2        3        4
Row2        5        6        7        8
Row3        9       10       11       12

Columns 1 and 2 (using iloc):
       Column2  Column3
Row1     

In [ ]:
# read csv file
df = pd.read_csv('sales_data_sample.csv', encoding='latin1')
print(df)

# Display the first few rows of the DataFrame
print(df.head())

   ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0        10107               30      95.70                2  2871.00   
1        10121               34      81.35                5  2765.90   
2        10134               41      94.74                2  3884.34   
3        10145               45      83.26                6  3746.70   
4        10159               49     100.00               14  5205.27   

         ORDERDATE   STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0   2/24/2003 0:00  Shipped       1         2     2003  ...   
1    5/7/2003 0:00  Shipped       2         5     2003  ...   
2    7/1/2003 0:00  Shipped       3         7     2003  ...   
3   8/25/2003 0:00  Shipped       3         8     2003  ...   
4  10/10/2003 0:00  Shipped       4        10     2003  ...   

                    ADDRESSLINE1  ADDRESSLINE2           CITY STATE  \
0        897 Long Airport Avenue           NaN            NYC    NY   
1             59 rue de l'Abbaye           NaN

In [9]:
# read csv file
df = pd.read_csv('sales_data_sample.csv', encoding='latin1')

# Display the last few rows of the DataFrame
print(df.tail())

      ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
2818        10350               20     100.00               15  2244.40   
2819        10373               29     100.00                1  3978.51   
2820        10386               43     100.00                4  5417.57   
2821        10397               34      62.24                1  2116.16   
2822        10414               47      65.52                9  3079.44   

           ORDERDATE    STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
2818  12/2/2004 0:00   Shipped       4        12     2004  ...   
2819  1/31/2005 0:00   Shipped       1         1     2005  ...   
2820   3/1/2005 0:00  Resolved       1         3     2005  ...   
2821  3/28/2005 0:00   Shipped       1         3     2005  ...   
2822   5/6/2005 0:00   On Hold       2         5     2005  ...   

               ADDRESSLINE1  ADDRESSLINE2      CITY STATE POSTALCODE  COUNTRY  \
2818     C/ Moralzarzal, 86           NaN    Madrid   NaN      28034   

In [10]:
# read csv file
df = pd.read_csv('sales_data_sample.csv', encoding='latin1')

# display all headers 
print(df.columns)

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='object')


In [27]:
# read csv file
df = pd.read_csv('sales_data_sample.csv', encoding='latin1')

# display all distinct values in a column
print(df['CITY'].unique())

['NYC' 'Reims' 'Paris' 'Pasadena' 'San Francisco' 'Burlingame' 'Lille'
 'Bergen' 'Melbourne' 'Newark' 'Bridgewater' 'Nantes' 'Cambridge'
 'Helsinki' 'Stavern' 'Allentown' 'Salzburg' 'Chatswood' 'New Bedford'
 'Liverpool' 'Madrid' 'Lule' 'Singapore' 'South Brisbane' 'Philadelphia'
 'Lyon' 'Vancouver' 'Burbank' 'New Haven' 'Minato-ku' 'Torino' 'Boras'
 'Versailles' 'San Rafael' 'Nashua' 'Brickhaven' 'North Sydney' 'Montreal'
 'Osaka' 'White Plains' 'Kobenhavn' 'London' 'Toulouse' 'Barcelona'
 'Los Angeles' 'San Diego' 'Bruxelles' 'Tsawassen' 'Boston' 'Cowes' 'Oulu'
 'San Jose' 'Graz' 'Makati City' 'Marseille' 'Koln' 'Gensve'
 'Reggio Emilia' 'Frankfurt' 'Espoo' 'Dublin' 'Manchester' 'Aaarhus'
 'Glendale' 'Sevilla' 'Brisbane' 'Strasbourg' 'Las Vegas' 'Oslo' 'Bergamo'
 'Glen Waverly' 'Munich' 'Charleroi']


In [16]:
# read csv file
df = pd.read_csv('sales_data_sample.csv', encoding='latin1')

# Display columns that have null values
null_columns = df.columns[df.isnull().any()]
print("Columns with null values:", null_columns)

# Display columns that have specific value NA
na_columns = df.columns[df.isna().any()]
print("Columns with NA values:", na_columns)

# Display columns that have specific value NY
ny_columns = df.columns[df.isin(['NY']).any()]
print("Columns with NY values:", ny_columns)

Columns with null values: Index(['ADDRESSLINE2', 'STATE', 'POSTALCODE', 'TERRITORY'], dtype='object')
Columns with NA values: Index(['ADDRESSLINE2', 'STATE', 'POSTALCODE', 'TERRITORY'], dtype='object')
Columns with NY values: Index(['STATE'], dtype='object')


In [21]:
# read csv file
df = pd.read_csv('sales_data_sample.csv', encoding='latin1')

# Display rows that have null values
null_rows = df[df.isnull().any(axis=1)]
print("Rows with null values:\n", null_rows)

Rows with null values:
       ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0           10107               30      95.70                2  2871.00   
1           10121               34      81.35                5  2765.90   
2           10134               41      94.74                2  3884.34   
3           10145               45      83.26                6  3746.70   
4           10159               49     100.00               14  5205.27   
...           ...              ...        ...              ...      ...   
2818        10350               20     100.00               15  2244.40   
2819        10373               29     100.00                1  3978.51   
2820        10386               43     100.00                4  5417.57   
2821        10397               34      62.24                1  2116.16   
2822        10414               47      65.52                9  3079.44   

            ORDERDATE    STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0      2

In [25]:
# read csv file
df = pd.read_csv('sales_data_sample.csv', encoding='latin1')

# Display rows that have NY values
NY_rows = df[df.isin(['NY']).any(axis=1)]
print("Rows with NY values:\n", NY_rows)

Rows with NY values:
       ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0           10107               30      95.70                2  2871.00   
11          10237               23     100.00                7  2333.12   
19          10329               42     100.00                1  4396.14   
31          10163               21     100.00                1  4860.24   
54          10107               39      99.91                5  3896.49   
...           ...              ...        ...              ...      ...   
2737        10337               36      71.89                7  2588.04   
2759        10308               39      68.11               15  2656.29   
2788        10329               44      86.13                8  3789.72   
2809        10248               23      65.52                9  1506.96   
2817        10337               42      97.16                5  4080.72   

            ORDERDATE     STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0      2/

In [36]:
# read csv file
df = pd.read_csv('sales_data_sample.csv', encoding='latin1')

# Display Max Sales
max_sales = df['SALES'].max()
print("Max Sales:", max_sales)

# Display Min Sales
min_sales = df['SALES'].min()
print("Min Sales:", min_sales)

# Display Average Sales
avg_sales = df['SALES'].mean()
print("Average Sales:", avg_sales)

# display Sum of Sales per Year
sales_per_year = df.groupby('YEAR_ID')['SALES'].sum()
print("Sum of Sales per Year:\n", sales_per_year)

Max Sales: 14082.8
Min Sales: 482.13
Average Sales: 3553.889071909316
Sum of Sales per Year:
 YEAR_ID
2003    3516979.54
2004    4724162.60
2005    1791486.71
Name: SALES, dtype: float64


In [40]:
# Sample employee data
data = {
    "name": ["Alice", "Bob", "Charlie", "Diana", "Ethan", "Fiona", "George", "Hannah", "Ian", "Julia"],
    "age": [25, 30, 28, 35, 40, 29, 32, 27, 38, 26],
    "salary": [50000, 60000, 55000, 75000, 80000, 58000, 62000, 54000, 78000, 52000],
    "performance_score": [8, 7, 9, 6, 8, 7, 8, 9, 6, 7]
}

# Create DataFrame
employees_df = pd.DataFrame(data)

# Add new calculated column 'bonus'
employees_df['bonus'] = employees_df['salary'] * (employees_df['performance_score'] / 100)
print("Employees DataFrame with Bonus:\n", employees_df)

# add new column Total salary
employees_df['total_salary'] = employees_df['salary'] + employees_df['bonus']
print("Employees DataFrame with Total Salary:\n", employees_df)

Employees DataFrame with Bonus:
       name  age  salary  performance_score   bonus
0    Alice   25   50000                  8  4000.0
1      Bob   30   60000                  7  4200.0
2  Charlie   28   55000                  9  4950.0
3    Diana   35   75000                  6  4500.0
4    Ethan   40   80000                  8  6400.0
5    Fiona   29   58000                  7  4060.0
6   George   32   62000                  8  4960.0
7   Hannah   27   54000                  9  4860.0
8      Ian   38   78000                  6  4680.0
9    Julia   26   52000                  7  3640.0
Employees DataFrame with Total Salary:
       name  age  salary  performance_score   bonus  total_salary
0    Alice   25   50000                  8  4000.0       54000.0
1      Bob   30   60000                  7  4200.0       64200.0
2  Charlie   28   55000                  9  4950.0       59950.0
3    Diana   35   75000                  6  4500.0       79500.0
4    Ethan   40   80000                  